package com.invoiceme.invoice.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * Request DTO for creating an invoice.
 */
public record CreateInvoiceRequest(
    @NotNull(message = "Customer ID is required")
    UUID customerId,

    @NotEmpty(message = "At least one line item is required")
    @Valid
    List<LineItemDto> lineItems,

    @NotNull(message = "Issue date is required")
    LocalDate issueDate,

    @NotNull(message = "Due date is required")
    LocalDate dueDate,

    @NotNull(message = "Tax rate is required")
    @PositiveOrZero(message = "Tax rate must be positive or zero")
    BigDecimal taxRate,

    String notes
) {
    /**
     * DTO for a line item in the request.
     */
    public record LineItemDto(
        @NotNull(message = "Description is required")
        String description,

        @NotNull(message = "Quantity is required")
        @PositiveOrZero(message = "Quantity must be positive")
        BigDecimal quantity,

        @NotNull(message = "Unit price amount is required")
        @PositiveOrZero(message = "Unit price must be positive or zero")
        @JsonProperty("unitPriceAmount")
        BigDecimal unitPriceAmount,

        @NotNull(message = "Unit price currency is required")
        @JsonProperty("unitPriceCurrency")
        String unitPriceCurrency // ISO 4217 currency code (e.g., "USD")
    ) {}

    /**
     * Converts this DTO to a CreateInvoiceCommand.
     *
     * @param id the invoice ID (generated by controller)
     * @return CreateInvoiceCommand
     */
    public com.invoiceme.invoice.application.commands.CreateInvoiceCommand toCommand(UUID id) {
        List<com.invoiceme.invoice.application.commands.CreateInvoiceCommand.LineItemDto> commandLineItems =
            lineItems.stream()
                .map(li -> new com.invoiceme.invoice.application.commands.CreateInvoiceCommand.LineItemDto(
                    li.description(),
                    li.quantity(),
                    li.unitPriceAmount(),
                    li.unitPriceCurrency()
                ))
                .toList();

        return new com.invoiceme.invoice.application.commands.CreateInvoiceCommand(
            id,
            customerId,
            commandLineItems,
            issueDate,
            dueDate,
            taxRate,
            notes
        );
    }
}

