package com.invoiceme.invoice.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Request DTO for recording a payment against an invoice.
 */
public record RecordPaymentRequest(
    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be positive")
    BigDecimal amount,

    @NotNull(message = "Currency is required")
    String currency, // ISO 4217 currency code (e.g., "USD")

    @NotNull(message = "Payment date is required")
    @JsonProperty("paymentDate")
    LocalDate paymentDate,

    @NotBlank(message = "Payment method is required")
    String method, // e.g., "Bank Transfer", "Credit Card", "Cash"

    String reference // optional transaction reference
) {
    /**
     * Converts this DTO to a RecordPaymentCommand.
     *
     * @param invoiceId the invoice ID
     * @param paymentId the payment ID (generated by controller)
     * @return RecordPaymentCommand
     */
    public com.invoiceme.invoice.application.commands.RecordPaymentCommand toCommand(
        java.util.UUID invoiceId,
        java.util.UUID paymentId
    ) {
        return new com.invoiceme.invoice.application.commands.RecordPaymentCommand(
            invoiceId,
            paymentId,
            amount,
            currency,
            paymentDate,
            method,
            reference
        );
    }
}

