package com.invoiceme.customer.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Request DTO for creating a customer.
 */
public record CreateCustomerRequest(
    @NotBlank(message = "Name is required")
    String name,

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    String email,

    String phone,

    @NotNull(message = "Address is required")
    @Valid
    AddressDto address,

    @NotBlank(message = "Payment terms are required")
    String paymentTerms
) {
    public record AddressDto(
        String street,
        String city,
        @JsonProperty("postalCode")
        String postalCode,
        String country
    ) {}

    /**
     * Converts this DTO to a CreateCustomerCommand.
     * 
     * @param id the customer ID (generated by controller)
     * @return CreateCustomerCommand
     */
    public com.invoiceme.customer.application.commands.CreateCustomerCommand toCommand(java.util.UUID id) {
        return new com.invoiceme.customer.application.commands.CreateCustomerCommand(
            id,
            name,
            email,
            address != null ? address.street() : null,
            address != null ? address.city() : null,
            address != null ? address.postalCode() : null,
            address != null ? address.country() : null,
            phone,
            paymentTerms
        );
    }
}

